### ISSUE TITLE
Where did setCountDown() go?

### ISSUE THREAD

**Issue by tierra** [Panmind/jquery-countdown#1]
Just curious what the replacement for this is in your version.

**Comment by vjt** [comment]
Hi man,

the method was stripped of the _javish_ `set` prefix and became just `countDown`. :-)

**Comment by tierra** [comment]
I did see that, specifically with startCountDown() => countDown('start') and stopCountDown() => countDown('stop'), but there's nothing in your version for resetting the targetOffset/targetTime to a new value as was previously done in the original version with setCountDown().

**Comment by vjt** [comment]
aha - sorry, I didn't understand your question correctly.

Yes, you're right, the setting of parameters is done only during initialization, but it is easy to move that code into a new set: function () and then call countDown ('set', parameters). 

I don't have resources right now to do that, but if you do and send a pull request I'll happily merge it.

Thanks!

~Marcello
